personal:
    lastName: 渣渣辉
    age: 888
    boss: true
    birthday: 2017/7/07
    maps: {k1: v1,k2: v2}
    lists:
        - zhaoliu
        - lisi
        - wangwu
    dog:
      name: 小狗崽
      age: 666
